Create new API for getting images outside of WebView.
immichFrame/ImmichFrame pull request #228
Opened 2024-12-10 00:33 UTC by 3rob3

2024-12-10 15:53 UTC, JW-CH requested changes

2024-12-10 15:53 UTC, JW-CH commented on ImmichFrame.WebApi/ImmichFrame.WebApi.csproj
> +    <SpaProxyLaunchCommand>npm run dev -- --host</SpaProxyLaunchCommand>
Is this line needed in the default?

2024-12-10 15:53 UTC, JW-CH commented on ImmichFrame.WebApi/Controllers/AssetController.cs
> +            using (MemoryStream memoryStream = new MemoryStream())
Image already returns a stream, why is a memory stream needed here?

2024-12-10 15:53 UTC, JW-CH commented on ImmichFrame.WebApi/Controllers/AssetController.cs
> +            return Ok(new
I don't like the `Ok()`. Can't you just return a class/tuple?

2024-12-10 15:53 UTC, JW-CH commented on ImmichFrame.WebApi/Controllers/AssetController.cs
> +            using (var memoryStream = (MemoryStream)randomImage.ThumbhashImage!)
Can't you just access `randomImage.Thumbhash` here?

2024-12-10 15:53 UTC, JW-CH commented on ImmichFrame.WebApi/Controllers/AssetController.cs
> +        public async Task<IActionResult> GetRandomImage()
Return actual class/object instead of action result.

2024-12-10 15:53 UTC, JW-CH commented on ImmichFrame.WebApi/Controllers/AssetController.cs
> +        public async Task<IActionResult> GetRandomImage()
Also, maybe change the naming? This returns more than just an image (image, metadata)

2024-12-10 15:53 UTC, JW-CH commented on ImmichFrame.WebApi/Controllers/AssetController.cs
> +            return Ok(new
Maybe return an imagestream and the full `AssetResponseDto`?

2024-12-10 16:18 UTC, 3rob3 commented on ImmichFrame.WebApi/Controllers/AssetController.cs
> +            return Ok(new
> I don't like the `Ok()`. Can't you just return a class/tuple?

this is how am ensuring we get an http Ok response. Seemed like good practice Why do you "not like" it?

2024-12-10 16:20 UTC, 3rob3 commented on ImmichFrame.WebApi/ImmichFrame.WebApi.csproj
> +    <SpaProxyLaunchCommand>npm run dev -- --host</SpaProxyLaunchCommand>
> Is this line needed in the default?

Impossible to debug from another device on network without it. whats the issue?

2024-12-10 16:33 UTC, 3rob3 commented on ImmichFrame.WebApi/Controllers/AssetController.cs
> +            using (MemoryStream memoryStream = new MemoryStream())
fileStream is not seekable, or directly convertible to byte array. This was only way I got it to work. Feel free to suggest an alternative.

2024-12-10 16:44 UTC, 3rob3 commented on ImmichFrame.WebApi/Controllers/AssetController.cs
> +            using (var memoryStream = (MemoryStream)randomImage.ThumbhashImage!)
> Can't you just access `randomImage.Thumbhash` here?

Yes I can fix

2024-12-10 20:14 UTC, 3rob3 commented on ImmichFrame.WebApi/Controllers/AssetController.cs
> +        public async Task<IActionResult> GetRandomImage()
> Return actual class/object instead of action result.

this is how am ensuring we get an http Ok response. Seemed like good practice

2024-12-10 20:14 UTC, 3rob3 commented on ImmichFrame.WebApi/Controllers/AssetController.cs
> +        public async Task<IActionResult> GetRandomImage()
> Also, maybe change the naming? This returns more than just an image (image, metadata)

done

2024-12-10 21:37 UTC, JW-CH commented on ImmichFrame.WebApi/ImmichFrame.WebApi.csproj
> +    <SpaProxyLaunchCommand>npm run dev -- --host</SpaProxyLaunchCommand>
> > Is this line needed in the default?
> 
> Impossible to debug from another device on network without it. whats the issue?

You are right. This is debug only. I just thought we keep it minimal and if you need to debug, you could just add it. I thought this may could cause issues, and usually we do not need to debug from another device. But I am ok with it!

2024-12-11 09:06 UTC, JW-CH requested changes

2024-12-11 09:06 UTC, JW-CH commented on ImmichFrame.WebApi/Controllers/AssetController.cs
> +            var image = await _logic.GetImage(new Guid(randomImage.Id));
Can you add the webhook notification here?

```cs
var notification = new ImageRequestedNotification(new Guid(randomImage.Id));
_ = _logic.SendWebhookNotification(notification);
```

2024-12-11 09:06 UTC, JW-CH commented on ImmichFrame.WebApi/Controllers/AssetController.cs
> +            //var randomImageUrl = Url.Action("GetRandomImage", null, new { id = randomImage.Id }, Request.Scheme);
Remove unused code :)

2024-12-11 09:06 UTC, JW-CH commented on ImmichFrame.WebApi/Controllers/AssetController.cs
> +            var locationParts = _settings.ImageLocationFormat?.Split(',') ?? Array.Empty<string>();
If I want to change the order e.g. `country, city, state` this will not work.

Why not just replace all `city`, `state`, `country` in the `ImageLocationFormat`?

2024-12-11 09:06 UTC, JW-CH commented on ImmichFrame.WebApi/Controllers/AssetController.cs
> +            var locationParts = _settings.ImageLocationFormat?.Split(',') ?? Array.Empty<string>();
This would also allow more custom `ImageLocationFormat`s like `I was in city, country`

2024-12-11 12:13 UTC, 3rob3 commented on ImmichFrame.WebApi/Controllers/AssetController.cs
> +            var image = await _logic.GetImage(new Guid(randomImage.Id));
done

2024-12-11 12:13 UTC, 3rob3 commented on ImmichFrame.WebApi/Controllers/AssetController.cs
> +            //var randomImageUrl = Url.Action("GetRandomImage", null, new { id = randomImage.Id }, Request.Scheme);
done

2024-12-11 12:18 UTC, 3rob3 commented on ImmichFrame.WebApi/Controllers/AssetController.cs
> +            var locationParts = _settings.ImageLocationFormat?.Split(',') ?? Array.Empty<string>();
not sure I fully understood. Hopefully this is what you meant. 
- Do you remember why we had the extra split in State? 
- Do we need to implement Country shortening via ISO 3 digit codes like we used to have? I always disable Country or else it comes out as "United States of America", which is ridiculous.

2024-12-11 19:50 UTC, 3rob3 commented on ImmichFrame.WebApi/Controllers/AssetController.cs
> +            var locationParts = _settings.ImageLocationFormat?.Split(',') ?? Array.Empty<string>();
Done, also fixed (I think) wrong Settings using injection.

2024-12-11 21:01 UTC, JW-CH approved these changes

2024-12-11 21:01 UTC, merged